export const products = [
    { id: '1', name: 'Abacate' },
    { id: '2', name: 'Abacaxi' },
    { id: '3', name: 'Abóbora Seca' },
    { id: '4', name: 'Abobrinha' },
    { id: '5', name: 'Acelga' },
    { id: '6', name: 'Alho' },
    { id: '7', name: 'Ameixa' },
    { id: '8', name: 'Banana 16Kg' },
    { id: '9', name: 'Banana Maçã' },
    { id: '10', name: 'Banana Prata' },
    { id: '11', name: 'Batata' },
    { id: '12', name: 'Batata Doce' },
    { id: '13', name: 'Batata Salsa' },
    { id: '14', name: 'Berinjela' },
    { id: '15', name: 'Beterraba' },
    { id: '16', name: 'Brócolis' },
    { id: '17', name: 'Cabotia' },
    { id: '18', name: 'Caqui' },
    { id: '19', name: 'Cebola' },
    { id: '20', name: 'Cenoura' },
    { id: '21', name: 'Chuchu' },
    { id: '22', name: 'Coco' },
    { id: '23', name: 'Couve Flor' },
    { id: '24', name: 'Gengibre' },
    { id: '25', name: 'Goiaba' },
    { id: '26', name: 'Jiló' },
    { id: '27', name: 'Kiwi' },
    { id: '28', name: 'Laranja Bahia' },
    { id: '29', name: 'Laranja Lima' },
    { id: '30', name: 'Laranja Pêra' },
    { id: '31', name: 'Limão' },
    { id: '32', name: 'Maçã Arg.' },
    { id: '33', name: 'Maçã Fugi' },
    { id: '34', name: 'Maçã Gala' },
    { id: '35', name: 'Mamão Formosa' },
    { id: '36', name: 'Mamão Hawai' },
    { id: '37', name: 'Manga' },
    { id: '38', name: 'Maracujá' },
    { id: '39', name: 'Melancia' },
    { id: '40', name: 'Melão' },
    { id: '41', name: 'Melão Rei' },
    { id: '42', name: 'Mexirica' },
    { id: '43', name: 'Moranga' },
    { id: '44', name: 'Moranguinho' },
    { id: '45', name: 'Morgote' },
    { id: '46', name: 'Nectarina' },
    { id: '47', name: 'Pepino' },
    { id: '48', name: 'Pepino Japonês' },
    { id: '49', name: 'Pêra' },
    { id: '50', name: 'Pêssego' },
    { id: '51', name: 'Pimentão Amarelo' },
    { id: '52', name: 'Pimentão Verde' },
    { id: '53', name: 'Pimentão Vermelho' },
    { id: '54', name: 'Ponkan' },
    { id: '55', name: 'Quiabo' },
    { id: '56', name: 'Repolho' },
    { id: '57', name: 'Repolho Roxo' },
    { id: '58', name: 'Tomate' },
    { id: '59', name: 'Tomate Médio' },
    { id: '60', name: 'Tomate Saladete' },
    { id: '61', name: 'Uva Benitaka' },
    { id: '62', name: 'Uva Itália' },
    { id: '63', name: 'Uva Niágara' },
    { id: '64', name: 'Vagem' },
    { id: '65', name: 'Inhame' },
    { id: '66', name: 'Ovo' },
    { id: '67', name: 'Pamonha' }
]

export const productsSorted = products.sort((a, b) => a.name.localeCompare(b.name))