export const products = [
    'Abacate',
    'Abacaxi',
    'Abóbora Seca',
    'Abobrinha',
    'Acelga',
    'Alho',
    'Ameixa',
    'Banana 16Kg Col.',
    'Banana Maçã',
    'Banann Prata',
    'Batata',
    'Batata Doce',
    'Batata Salsa',
    'Berinjela',
    'Beterraba',
    'Brócolis',
    'Cabotia',
    'Caqui',
    'Cebola',
    'Cenoura',
    'Chuchu',
    'Coco',
    'Couve Flor',
    'Gengibre',
    'Goiaba',
    'Jiló',
    'Kiwi',
    'Laranja Bahia',
    'Laranja Lima',
    'Laranja Pêra',
    'Limão',
    'Maçã Arg.',
    'Maçã Fugi',
    'Maçã Gala',
    'Mamão Formosa',
    'Mamão Hawai',
    'Manga',
    'Maracujá',
    'Melancia',
    'Melão',
    'Melão Rei',
    'Mexirica',
    'Moranga',
    'Moranguinho',
    'Morgote',
    'Nectarina',
    'Pepino',
    'Pepino Japonês',
    'Pêra',
    'Pêssego',
    'Pimentão Amarelo',
    'Pimentão Verde',
    'Pimentão Vermelho',
    'Ponkan',
    'Quiabo',
    'Repolho',
    'Repolho Roxo',
    'Tomate',
    'Tomate Médio',
    'Tomate Saladete',
    'Uva Benitaka',
    'Uva Itália',
    'Uva Niágara',
    'Vagem',
]